name: Node CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.16.x]

    steps:
      - uses: actions/checkout@v1

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      
      - name: npm install
        run: npm install
        env:
          CI: true

      - name: TSLint
        run: npm run lint
        env:
          CI: true

      - name: stylelint
        run: npm run stylelint
        env:
          CI: true

      - name: format
        run: npm run prettier:check
        env:
          CI: true

      - name: build
        run: npm run build --prod
        env:
          CI: true

      - name: unit test
        run: npm run test:ci
        env:
          CI: true

      - name: Archive code coverage results
        uses: actions/upload-artifact@v1
        with:
          name: code-coverage-report
          path: coverage

      - name: e2e test
        run: npm run e2e:ci
        env:
          CI: true